version: "3"

services:
  app:
    volumes:
      - ${PWD}/apps/assets/js:/usr/share/nginx/js:ro
      - ${PWD}/apps/assets/css:/usr/share/nginx/css:ro
      - ${PWD}/apps/v1:/usr/share/nginx/html:ro
      # - ${PWD}/apps/v2:/usr/share/nginx/html:ro
      # - ${PWD}/apps/v3:/usr/share/nginx/html:ro
      - ${PWD}/conf/nginx.conf:/etc/nginx/conf.d/default.conf
