version: "3"

services:
  app:
    image: kryptoblack/docker-swarm-demo:v1
    configs:
      - source: nginx.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:433
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        order: stop-first

  redis:
    image: redis
    ports:
      - "6379:6379"
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        order: stop-first
      placement:
        constraints:
          - node.role == manager

configs:
  nginx.conf:
    file: configs/nginx/nginx.conf
