version: "3"

services:
  # app:
  #   image: nginx
  #   ports:
  #     - "80:80"
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #     update_config:
  #       parallelism: 1
  #       failure_action: rollback
  #       order: stop-first
  #   configs:
  #     - source: v1-index.html
  #       target: /usr/share/nginx/html/index.html
  #     - source: favicon
  #       target: /usr/share/nginx/html/favicon.ico
  #     - source: nginx.conf
  #       target: /etc/nginx/conf.d/nginx.conf
  #   volumes:
  #     - ./apps/assets/js:/usr/share/nginx/js:ro
  #     - ./apps/assets/css:/usr/share/nginx/css:ro
  app:
    image: kryptoblack/docker-swarm-demo:v1
    ports:
      - 80:80
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        order: stop-first
    links:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        order: stop-first
      placement:
        constraints:
          - node.role == manager
  # configs:
  #   v1-index.html:
  #     name: v1-index.html
  #     file: apps/v1/index.html
  #   favicon:
  #     name: favicon
  #     file: apps/assets/favicon.ico
  #   nginx.conf:
  #     name: nginx.conf
  #     file: apps/conf/nginx.conf
